apiVersion: apps/v1
kind: Deployment
metadata:
  name: petapp
  labels:
    app: petapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petapp
  template:
    metadata:
      labels:
        app: petapp
    spec:
      containers:
        - name: petapp
          image: stephenshenk/petapp:latest
          ports:
            - containerPort: 3000
